// ملف البيانات الوهمية للسوق المصري - TASKKASH Egypt
// جميع الأسعار بالجنيه المصري (EGP)

export interface Task {
  id: string;
  title: string;
  advertiser: string;
  advertiserLogo: string;
  category: 'survey' | 'video' | 'app' | 'social' | 'visit' | 'photo';
  reward: number;
  duration: string;
  description: string;
  requirements: string[];
  steps: string[];
  location?: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'advanced';
  status: 'available' | 'in_progress' | 'completed';
  deadline?: string;
}

// المهام المصرية - 35 مهمة متنوعة
export const egyptianTasks: Task[] = [
  // القسم 1: مهام التطبيقات الرقمية (8 مهام)
  {
    id: 'EG001',
    title: 'تثبيت تطبيق Jumia واستخدامه',
    advertiser: 'Jumia Egypt',
    advertiserLogo: '/logos/jumia.png',
    category: 'app',
    reward: 50,
    duration: '10 دقائق',
    difficulty: 'medium',
    status: 'available',
    description: 'حمّل تطبيق Jumia، أنشئ حساب جديد، وتصفح قسم العروض اليومية',
    requirements: [
      'هاتف Android أو iOS',
      'مقيم في مصر',
      'حساب جديد (لم يسبق التسجيل)',
    ],
    steps: [
      'حمّل تطبيق Jumia من Google Play أو App Store',
      'أنشئ حساباً جديداً برقم هاتفك المصري',
      'تصفح قسم "العروض اليومية" لمدة دقيقتين',
      'التقط لقطة شاشة لصفحة حسابك الشخصي',
      'ارفع لقطة الشاشة كإثبات',
    ],
  },
  {
    id: 'EG002',
    title: 'تثبيت تطبيق Vodafone Cash',
    advertiser: 'Vodafone Egypt',
    advertiserLogo: '/logos/vodafone.png',
    category: 'app',
    reward: 60,
    duration: '15 دقيقة',
    difficulty: 'medium',
    status: 'available',
    description: 'حمّل تطبيق Vodafone Cash وأنشئ حساباً جديداً',
    requirements: [
      'هاتف Android أو iOS',
      'رقم فودافون مصري',
      'مقيم في مصر',
    ],
    steps: [
      'حمّل تطبيق Vodafone Cash',
      'أنشئ حساباً جديداً',
      'أكمل التسجيل بإدخال بياناتك',
      'التقط لقطة شاشة للصفحة الرئيسية',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG003',
    title: 'تثبيت تطبيق Noon وإضافة منتج للسلة',
    advertiser: 'Noon Egypt',
    advertiserLogo: '/logos/noon.png',
    category: 'app',
    reward: 45,
    duration: '8 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'حمّل تطبيق Noon، تصفح المنتجات، وأضف منتجاً للسلة',
    requirements: [
      'هاتف Android أو iOS',
      'مقيم في مصر',
    ],
    steps: [
      'حمّل تطبيق Noon',
      'تصفح قسم "الإلكترونيات"',
      'أضف أي منتج للسلة',
      'التقط لقطة شاشة للسلة',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG004',
    title: 'تثبيت تطبيق بنك مصر وإنشاء حساب',
    advertiser: 'بنك مصر',
    advertiserLogo: '/logos/banque-misr.png',
    category: 'app',
    reward: 80,
    duration: '15 دقيقة',
    difficulty: 'medium',
    status: 'available',
    description: 'حمّل تطبيق بنك مصر وأنشئ حساباً رقمياً',
    requirements: [
      'مواطن مصري',
      'بطاقة رقم قومي',
    ],
    steps: [
      'حمّل تطبيق بنك مصر',
      'أنشئ حساباً رقمياً',
      'أكمل التسجيل',
      'التقط لقطة شاشة للصفحة الرئيسية',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG005',
    title: 'تثبيت تطبيق Classera والتسجيل',
    advertiser: 'Classera Egypt',
    advertiserLogo: '/logos/classera.png',
    category: 'app',
    reward: 50,
    duration: '10 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'حمّل تطبيق Classera وأنشئ حساباً كطالب',
    requirements: [
      'طالب أو مهتم بالتعليم الإلكتروني',
    ],
    steps: [
      'حمّل تطبيق Classera',
      'أنشئ حساباً جديداً',
      'تصفح الدورات المتاحة',
      'التقط لقطة شاشة',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG006',
    title: 'تثبيت لعبة جديدة واللعب لمدة 10 دقائق',
    advertiser: 'مطور ألعاب مصري',
    advertiserLogo: '/logos/game-dev.png',
    category: 'app',
    reward: 40,
    duration: '15 دقيقة',
    difficulty: 'easy',
    status: 'available',
    description: 'حمّل لعبة جديدة والعب لمدة 10 دقائق',
    requirements: [
      'هاتف Android أو iOS',
    ],
    steps: [
      'حمّل اللعبة',
      'العب لمدة 10 دقائق',
      'التقط لقطة شاشة من اللعبة',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG007',
    title: 'تثبيت تطبيق صحي وتسجيل نشاطك اليومي',
    advertiser: 'تطبيق صحي مصري',
    advertiserLogo: '/logos/health-app.png',
    category: 'app',
    reward: 120,
    duration: '3 أيام (5 دقائق يومياً)',
    difficulty: 'advanced',
    status: 'available',
    description: 'حمّل تطبيق صحي وسجّل نشاطك اليومي لمدة 3 أيام',
    requirements: [
      'مهتم بالصحة واللياقة',
    ],
    steps: [
      'حمّل التطبيق',
      'سجّل نشاطك اليومي (خطوات، طعام، نوم)',
      'استمر لمدة 3 أيام',
      'التقط لقطة شاشة للتقرير',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG008',
    title: 'استخدام Careem وكتابة تقييم',
    advertiser: 'Careem Egypt',
    advertiserLogo: '/logos/careem.png',
    category: 'app',
    reward: 70,
    duration: '20 دقيقة',
    difficulty: 'medium',
    status: 'available',
    description: 'اطلب رحلة عبر Careem واكتب تقييماً للتجربة (+ خصم 10% على الرحلة)',
    requirements: [
      'حساب Careem',
    ],
    steps: [
      'اطلب رحلة عبر Careem',
      'أكمل الرحلة',
      'اكتب تقييماً (50 كلمة)',
      'التقط لقطة شاشة',
      'ارفع لقطة الشاشة',
    ],
  },

  // القسم 2: مهام الاستبيانات (6 مهام)
  {
    id: 'EG009',
    title: 'استبيان حول عادات التسوق الإلكتروني',
    advertiser: 'Jumia Egypt',
    advertiserLogo: '/logos/jumia.png',
    category: 'survey',
    reward: 35,
    duration: '5 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'أجب على 8 أسئلة حول عادات التسوق الإلكتروني',
    requirements: [
      'العمر: 18-45 سنة',
      'مقيم في مصر',
    ],
    steps: [
      'اقرأ الأسئلة بعناية',
      'أجب على جميع الأسئلة بصدق',
      'أرسل الاستبيان',
    ],
  },
  {
    id: 'EG010',
    title: 'استبيان حول خدمات الاتصالات',
    advertiser: 'Orange Egypt',
    advertiserLogo: '/logos/orange.png',
    category: 'survey',
    reward: 40,
    duration: '6 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'أجب على 10 أسئلة حول خدمات الاتصالات والإنترنت',
    requirements: [
      'مستخدم خدمات اتصالات في مصر',
    ],
    steps: [
      'اقرأ الأسئلة بعناية',
      'أجب على جميع الأسئلة',
      'أرسل الاستبيان',
    ],
  },
  {
    id: 'EG011',
    title: 'استبيان حول المنتجات الصحية',
    advertiser: 'Nestlé Egypt',
    advertiserLogo: '/logos/nestle.png',
    category: 'survey',
    reward: 35,
    duration: '5 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'أجب على 7 أسئلة حول عادات استهلاك المنتجات الصحية',
    requirements: [
      'العمر: 25-40 سنة',
      'مهتم بالصحة واللياقة',
    ],
    steps: [
      'اقرأ الأسئلة بعناية',
      'أجب على جميع الأسئلة',
      'أرسل الاستبيان',
    ],
  },
  {
    id: 'EG012',
    title: 'استبيان حول الخدمات المصرفية الرقمية',
    advertiser: 'البنك الأهلي المصري',
    advertiserLogo: '/logos/nbe.png',
    category: 'survey',
    reward: 45,
    duration: '7 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'أجب على 10 أسئلة حول استخدامك للخدمات المصرفية الرقمية',
    requirements: [
      'مستخدم خدمات مصرفية',
    ],
    steps: [
      'اقرأ الأسئلة بعناية',
      'أجب على جميع الأسئلة',
      'أرسل الاستبيان',
    ],
  },
  {
    id: 'EG013',
    title: 'استبيان حول التعليم الإلكتروني',
    advertiser: 'Edraak Egypt',
    advertiserLogo: '/logos/edraak.png',
    category: 'survey',
    reward: 40,
    duration: '6 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'أجب على 8 أسئلة حول تجربتك مع التعليم الإلكتروني',
    requirements: [
      'طالب أو مهتم بالتعليم',
    ],
    steps: [
      'اقرأ الأسئلة بعناية',
      'أجب على جميع الأسئلة',
      'أرسل الاستبيان',
    ],
  },
  {
    id: 'EG014',
    title: 'استبيان حول تطبيق TASKKASH نفسه',
    advertiser: 'TASKKASH',
    advertiserLogo: '/logos/taskkash.png',
    category: 'survey',
    reward: 60,
    duration: '8 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'أجب على 10 أسئلة حول تجربتك مع تطبيق TASKKASH',
    requirements: [
      'مستخدم TASKKASH',
    ],
    steps: [
      'اقرأ الأسئلة بعناية',
      'أجب على جميع الأسئلة بصدق',
      'أرسل الاستبيان',
    ],
  },

  // القسم 3: مهام الفيديو والمحتوى (3 مهام)
  {
    id: 'EG015',
    title: 'مشاهدة فيديو إعلاني لتويوتا',
    advertiser: 'Toyota Egypt',
    advertiserLogo: '/logos/toyota.png',
    category: 'video',
    reward: 25,
    duration: '3 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'شاهد فيديو إعلاني لسيارة تويوتا الجديدة (30 ثانية) وأجب على 3 أسئلة',
    requirements: [
      'اتصال إنترنت جيد',
    ],
    steps: [
      'شاهد الفيديو بالكامل',
      'أجب على 3 أسئلة',
      'أرسل الإجابات',
    ],
  },
  {
    id: 'EG016',
    title: 'مشاهدة فيديو YouTube لـ Vodafone وكتابة تعليق',
    advertiser: 'Vodafone Egypt',
    advertiserLogo: '/logos/vodafone.png',
    category: 'video',
    reward: 50,
    duration: '8 دقائق',
    difficulty: 'medium',
    status: 'available',
    description: 'شاهد فيديو Vodafone على YouTube واكتب تعليقاً مفيداً',
    requirements: [
      'حساب YouTube',
    ],
    steps: [
      'شاهد الفيديو بالكامل',
      'اكتب تعليقاً مفيداً (20 كلمة على الأقل)',
      'التقط لقطة شاشة للتعليق',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG017',
    title: 'تقييم حملة إعلانية رقمية',
    advertiser: 'Purple Digital Marketing',
    advertiserLogo: '/logos/purple.png',
    category: 'video',
    reward: 55,
    duration: '10 دقائق',
    difficulty: 'medium',
    status: 'available',
    description: 'شاهد حملة إعلانية رقمية وقيّمها',
    requirements: [
      'مهتم بالتسويق الرقمي',
    ],
    steps: [
      'شاهد الحملة الإعلانية',
      'أجب على 5 أسئلة تقييمية',
      'اكتب ملاحظاتك (50 كلمة)',
      'ارفع التقييم',
    ],
  },

  // القسم 4: مهام وسائل التواصل الاجتماعي (3 مهام)
  {
    id: 'EG018',
    title: 'متابعة صفحة Jumia على Instagram',
    advertiser: 'Jumia Egypt',
    advertiserLogo: '/logos/jumia.png',
    category: 'social',
    reward: 20,
    duration: '2 دقيقة',
    difficulty: 'easy',
    status: 'available',
    description: 'تابع صفحة Jumia Egypt على Instagram',
    requirements: [
      'حساب Instagram',
    ],
    steps: [
      'افتح Instagram',
      'ابحث عن @JumiaEgypt',
      'اضغط "متابعة"',
      'التقط لقطة شاشة',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG019',
    title: 'مشاركة منشور Orange على Facebook',
    advertiser: 'Orange Egypt',
    advertiserLogo: '/logos/orange.png',
    category: 'social',
    reward: 25,
    duration: '3 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'شارك آخر منشور لـ Orange Egypt على صفحتك',
    requirements: [
      'حساب Facebook',
    ],
    steps: [
      'افتح صفحة Orange Egypt على Facebook',
      'شارك آخر منشور على صفحتك',
      'التقط لقطة شاشة للمنشور المشارك',
      'ارفع لقطة الشاشة',
    ],
  },
  {
    id: 'EG020',
    title: 'كتابة تغريدة عن تجربتك مع Uber',
    advertiser: 'Uber Egypt',
    advertiserLogo: '/logos/uber.png',
    category: 'social',
    reward: 40,
    duration: '5 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'اكتب تغريدة (تويت) عن تجربتك مع Uber في مصر',
    requirements: [
      'حساب X (Twitter)',
      'استخدام هاشتاج #UberEgypt',
    ],
    steps: [
      'اكتب تغريدة (50 كلمة على الأقل)',
      'أضف هاشتاج #UberEgypt',
      'انشر التغريدة',
      'التقط لقطة شاشة',
      'ارفع لقطة الشاشة',
    ],
  },

  // القسم 5: مهام التصوير (5 مهام - أونلاين)
  {
    id: 'EG021',
    title: 'تصوير إعلان بيبسي في الشارع',
    advertiser: 'PepsiCo Egypt',
    advertiserLogo: '/logos/pepsi.png',
    category: 'photo',
    reward: 50,
    duration: '10 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'ابحث عن إعلان بيبسي في الشارع (لوحة إعلانية) والتقط صورة واضحة له',
    requirements: [
      'كاميرا هاتف جيدة',
      'تفعيل GPS',
    ],
    steps: [
      'ابحث عن لوحة إعلانية لبيبسي في منطقتك',
      'التقط صورة واضحة تظهر الإعلان بالكامل',
      'تأكد من ظهور الموقع المحيط',
      'ارفع الصورة مع إحداثيات GPS',
    ],
  },
  {
    id: 'EG022',
    title: 'تصوير إعلان Coca-Cola في محطة مترو',
    advertiser: 'Coca-Cola Egypt',
    advertiserLogo: '/logos/coca-cola.png',
    category: 'photo',
    reward: 50,
    duration: '10 دقائق',
    difficulty: 'easy',
    status: 'available',
    description: 'التقط صورة لإعلان Coca-Cola في محطة مترو',
    location: 'محطة مترو',
    requirements: [
      'موقعك قريب من محطة مترو',
    ],
    steps: [
      'اذهب إلى محطة مترو',
      'ابحث عن إعلان Coca-Cola',
      'التقط صورة واضحة',
      'ارفع الصورة مع GPS',
    ],
  },

  // القسم 6: مهام ميدانية (Field Tasks) - 10 مهام بمكافآت عالية
  {
    id: 'EG023',
    title: 'زيارة فرع ماكدونالدز والحصول على خصم',
    advertiser: "McDonald's Egypt",
    advertiserLogo: '/logos/mcdonalds.png',
    category: 'visit',
    reward: 600,
    duration: '20 دقيقة',
    difficulty: 'medium',
    status: 'available',
    location: 'القاهرة، الجيزة',
    description: 'قم بزيارة أقرب فرع ماكدونالدز، التقط صورة من الداخل، واحصل على خصم 15%',
    requirements: [
      'موقعك في نطاق 5 كم من فرع ماكدونالدز',
      'تفعيل GPS',
    ],
    steps: [
      'اذهب إلى أقرب فرع ماكدونالدز',
      'افتح التطبيق وسجل دخولك (Check-in)',
      'التقط صورة من داخل المطعم',
      'اعرض الصورة عند الطلب للحصول على خصم 15%',
      'ارفع الصورة كإثبات',
    ],
  },
  {
    id: 'EG024',
    title: 'زيارة كارفور وتصوير قسم الأغذية',
    advertiser: 'Carrefour Egypt',
    advertiserLogo: '/logos/carrefour.png',
    category: 'visit',
    reward: 550,
    duration: '15 دقيقة',
    difficulty: 'easy',
    status: 'available',
    location: 'القاهرة، الإسكندرية',
    description: 'قم بزيارة فرع كارفور والتقط صورة لقسم الأغذية العضوية',
    requirements: [
      'موقعك في نطاق 10 كم من كارفور',
      'كاميرا هاتف جيدة',
    ],
    steps: [
      'اذهب إلى أقرب فرع كارفور',
      'ابحث عن قسم "الأغذية العضوية"',
      'التقط صورة واضحة للقسم',
      'تأكد من ظهور اللافتة في الصورة',
      'ارفع الصورة',
    ],
  },
  {
    id: 'EG025',
    title: 'زيارة معرض Hyundai وتصوير السيارات',
    advertiser: 'Hyundai Egypt',
    advertiserLogo: '/logos/hyundai.png',
    category: 'visit',
    reward: 800,
    duration: '25 دقيقة',
    difficulty: 'medium',
    status: 'available',
    location: 'القاهرة، الجيزة',
    description: 'قم بزيارة معرض Hyundai والتقط صور للسيارات المعروضة',
    requirements: [
      'موقعك قريب من معرض Hyundai',
      'كاميرا جيدة',
    ],
    steps: [
      'اذهب إلى أقرب معرض Hyundai',
      'التقط 3 صور لسيارات مختلفة',
      'تأكد من ظهور الأسعار',
      'ارفع الصور مع GPS',
    ],
  },
  {
    id: 'EG026',
    title: 'تجربة قيادة Nissan (Test Drive)',
    advertiser: 'Nissan Egypt',
    advertiserLogo: '/logos/nissan.png',
    category: 'visit',
    reward: 1500,
    duration: '45 دقيقة',
    difficulty: 'hard',
    status: 'available',
    location: 'القاهرة، الإسكندرية',
    description: 'احجز موعد تجربة قيادة لسيارة Nissan وشاركنا تجربتك',
    requirements: [
      'رخصة قيادة سارية',
      'العمر: 21+ سنة',
    ],
    steps: [
      'احجز موعد تجربة قيادة',
      'اذهب للمعرض وجرّب السيارة',
      'التقط صورة مع السيارة',
      'اكتب تقييم قصير (50 كلمة)',
      'ارفع الصورة والتقييم',
    ],
  },
  {
    id: 'EG027',
    title: 'زيارة KFC وتصوير القائمة الجديدة',
    advertiser: 'KFC Egypt',
    advertiserLogo: '/logos/kfc.png',
    category: 'visit',
    reward: 550,
    duration: '15 دقيقة',
    difficulty: 'easy',
    status: 'available',
    location: 'جميع المحافظات',
    description: 'قم بزيارة فرع KFC والتقط صورة للقائمة الجديدة',
    requirements: [
      'موقعك قريب من KFC',
    ],
    steps: [
      'اذهب إلى أقرب فرع KFC',
      'التقط صورة واضحة للقائمة الجديدة',
      'تأكد من ظهور الأسعار',
      'ارفع الصورة مع GPS',
    ],
  },
  {
    id: 'EG028',
    title: 'طلب وجبة من Talabat وكتابة تقييم',
    advertiser: 'Talabat Egypt',
    advertiserLogo: '/logos/talabat.png',
    category: 'visit',
    reward: 650,
    duration: '30 دقيقة',
    difficulty: 'medium',
    status: 'available',
    location: 'جميع المحافظات',
    description: 'اطلب وجبة عبر Talabat واكتب تقييماً للتجربة (+ خصم 15% على الطلب)',
    requirements: [
      'حساب Talabat',
      'موقعك في منطقة التوصيل',
    ],
    steps: [
      'اطلب وجبة عبر Talabat',
      'استلم الطلب',
      'اكتب تقييماً (50 كلمة)',
      'التقط صورة للوجبة',
      'ارفع الصورة والتقييم',
    ],
  },
  {
    id: 'EG029',
    title: 'تصوير منتجات Samsung في متجر',
    advertiser: 'Samsung Egypt',
    advertiserLogo: '/logos/samsung.png',
    category: 'visit',
    reward: 700,
    duration: '15 دقيقة',
    difficulty: 'easy',
    status: 'available',
    location: 'القاهرة، الإسكندرية',
    description: 'قم بزيارة متجر إلكترونيات والتقط صورة لمنتجات Samsung المعروضة',
    requirements: [
      'موقعك قريب من متجر إلكترونيات',
      'كاميرا جيدة',
    ],
    steps: [
      'اذهب إلى متجر إلكترونيات (مثل: B.TECH، eXtra)',
      'ابحث عن قسم Samsung',
      'التقط صورة واضحة للمنتجات المعروضة',
      'تأكد من ظهور الأسعار إن أمكن',
      'ارفع الصورة',
    ],
  },
  {
    id: 'EG030',
    title: 'تصوير منتجات Henkel في السوبرماركت',
    advertiser: 'Henkel Egypt',
    advertiserLogo: '/logos/henkel.png',
    category: 'visit',
    reward: 600,
    duration: '15 دقيقة',
    difficulty: 'easy',
    status: 'available',
    location: 'جميع المحافظات',
    description: 'قم بزيارة سوبرماركت والتقط صور لمنتجات Henkel (برسيل، بريل)',
    requirements: [
      'موقعك قريب من سوبرماركت',
    ],
    steps: [
      'اذهب إلى سوبرماركت (كارفور، هايبر وان، إلخ)',
      'ابحث عن منتجات Henkel',
      'التقط صورة واضحة للمنتجات',
      'تأكد من ظهور الأسعار',
      'ارفع الصورة',
    ],
  },
  {
    id: 'EG031',
    title: 'زيارة Spinneys وتقييم التجربة',
    advertiser: 'Spinneys Egypt',
    advertiserLogo: '/logos/spinneys.png',
    category: 'visit',
    reward: 750,
    duration: '20 دقيقة',
    difficulty: 'medium',
    status: 'available',
    location: 'القاهرة، الإسكندرية',
    description: 'قم بزيارة فرع Spinneys واكتب تقييماً للتجربة',
    requirements: [
      'موقعك في القاهرة أو الإسكندرية',
    ],
    steps: [
      'اذهب إلى أقرب فرع Spinneys',
      'تسوق لمدة 10 دقائق',
      'اكتب تقييماً (100 كلمة)',
      'التقط صورة من الداخل',
      'ارفع الصورة والتقييم',
    ],
  },
  {
    id: 'EG032',
    title: 'زيارة معرض عقاري وتصوير المشاريع',
    advertiser: 'شركة عقارات مصرية',
    advertiserLogo: '/logos/real-estate.png',
    category: 'visit',
    reward: 1000,
    duration: '30 دقيقة',
    difficulty: 'medium',
    status: 'available',
    location: 'القاهرة، الإسكندرية',
    description: 'قم بزيارة معرض عقاري والتقط صور للمشاريع المعروضة',
    requirements: [
      'موقعك في القاهرة أو الإسكندرية',
    ],
    steps: [
      'اذهب إلى معرض عقاري',
      'التقط صور للمشاريع',
      'اجمع كتيبات إن أمكن',
      'ارفع الصور',
    ],
  },

  // مهام إضافية (3 مهام)
  {
    id: 'EG033',
    title: 'تصوير قائمة طعام في Pizza Hut',
    advertiser: 'Pizza Hut Egypt',
    advertiserLogo: '/logos/pizza-hut.png',
    category: 'photo',
    reward: 55,
    duration: '10 دقائق',
    difficulty: 'easy',
    status: 'available',
    location: 'جميع المحافظات',
    description: 'قم بزيارة فرع Pizza Hut والتقط صورة لقائمة الطعام',
    requirements: [
      'موقعك قريب من Pizza Hut',
    ],
    steps: [
      'اذهب إلى أقرب فرع Pizza Hut',
      'التقط صورة واضحة لقائمة الطعام',
      'تأكد من ظهور الأسعار بوضوح',
      'ارفع الصورة مع إحداثيات GPS',
    ],
  },
  {
    id: 'EG034',
    title: 'زيارة مقهى Beano\'s والحصول على خصم',
    advertiser: "Beano's Café",
    advertiserLogo: '/logos/beanos.png',
    category: 'visit',
    reward: 600,
    duration: '20 دقيقة',
    difficulty: 'easy',
    status: 'available',
    location: 'القاهرة، الجيزة',
    description: 'قم بزيارة مقهى Beano\'s، التقط صورة من الداخل، واحصل على خصم 10%',
    requirements: [
      'موقعك في القاهرة أو الجيزة',
      'تفعيل GPS',
    ],
    steps: [
      'اذهب إلى أقرب فرع Beano\'s',
      'سجل دخولك عبر التطبيق',
      'التقط صورة من الداخل',
      'اعرض الصورة للحصول على خصم',
      'ارفع الصورة',
    ],
  },
  {
    id: 'EG035',
    title: 'زيارة Cairo Zoo Store وتصوير المنتجات',
    advertiser: 'Cairo Zoo Store',
    advertiserLogo: '/logos/cairo-zoo.png',
    category: 'visit',
    reward: 700,
    duration: '20 دقيقة',
    difficulty: 'easy',
    status: 'available',
    location: 'القاهرة',
    description: 'قم بزيارة Cairo Zoo Store والتقط صور للمنتجات',
    requirements: [
      'موقعك في القاهرة',
    ],
    steps: [
      'اذهب إلى Cairo Zoo Store',
      'التقط صور للمنتجات المتنوعة',
      'ارفع الصور',
    ],
  },
];

// إحصائيات المهام
export const taskStats = {
  totalTasks: egyptianTasks.length,
  totalRewards: egyptianTasks.reduce((sum, task) => sum + task.reward, 0),
  byCategory: {
    app: egyptianTasks.filter(t => t.category === 'app').length,
    survey: egyptianTasks.filter(t => t.category === 'survey').length,
    video: egyptianTasks.filter(t => t.category === 'video').length,
    social: egyptianTasks.filter(t => t.category === 'social').length,
    photo: egyptianTasks.filter(t => t.category === 'photo').length,
    visit: egyptianTasks.filter(t => t.category === 'visit').length,
  },
  byDifficulty: {
    easy: egyptianTasks.filter(t => t.difficulty === 'easy').length,
    medium: egyptianTasks.filter(t => t.difficulty === 'medium').length,
    hard: egyptianTasks.filter(t => t.difficulty === 'hard').length,
    advanced: egyptianTasks.filter(t => t.difficulty === 'advanced').length,
  },
};

// معلومات الاتصال المصرية
export const contactInfo = {
  email: 'support@taskkash.com',
  phone: '+20 100 158 1287',
  website: 'www.taskkash.com',
  currency: 'EGP',
  currencySymbol: 'ج.م',
  country: 'مصر',
  cities: ['القاهرة', 'الجيزة', 'الإسكندرية', 'الشرقية', 'القليوبية'],
};

export default egyptianTasks;

